sylius_grid:
    grids:
        app_admin_subscription:
            driver:
                options:
                    class: '%app.model.subscription.class%'
            fields:
                id:
                    type: string
                productName:
                    type: string
                    label: sylius.ui.product
                customer:
                    type: string
                    path: customer.email
                    label: sylius.ui.customer
                expirationTime:
                    type: datetime
                    options:
                        format: d-m-Y H:i:s
                    label: app.ui.expiration_time
