winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                create_subscriptions:
                    on: ['complete']
                    do: ['@App\Creator\SubscriptionCreatorInterface', 'fromOrder']
                    args: ['object']
    app_subscription:
        class: "%app.model.subscription.class%"
        graph: app_subscription
        state_machine_class: "%sylius.state_machine.class%"
        states:
            - active
            - expired
            - cancelled
        transitions:
            expire:
                from: [active]
                to: expired
            cancel:
                from: [active]
                to: cancelled
