sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_admin_subscription:
    resource: |
        alias: app.subscription
        only: ['index']
        templates: SyliusAdminBundle:Crud
        section: admin
        grid: app_admin_subscription
    type: sylius.resource
    prefix: /admin

app_admin_subcription_cancel:
    path: /subscriptions/{id}/cancel
    methods: [PUT]
    defaults:
        _controller: app.controller.subscription:applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: app_subscription
                transition: cancel
            redirect: referer
